# ASP.NET Core

# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'
  pathtosolution: 'Neon_Icon/'
  pathtoproject: 'Neon_Icon/WebClient'
  pathtotest: 'Neon_Icon/Testing'

  dockerId: 'revatureproject2neonicons'
  imageName: 'neonicons'

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'NeonIcons'
    organization: 'neoniconsproject2'
    scannerMode: 'MSBuild'
    projectKey: 'neoniconsproject2'
    projectName: 'Neon Icons'
    extraProperties: |
      sonar.cs.opencover.reportsPaths="$(Build.ArtifactStagingDirectory)/coverage/*"
      sonar.cs.vstest.reportsPaths="$(Build.ArtifactStagingDirectory)/test/*.trx"
  displayName: 'Sonar Prepare Analysis'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
  workingDirectory: $(pathtosolution)

- script: dotnet test
    --configuration $(buildConfiguration)
    --no-build
    --results-directory $(Build.ArtifactStagingDirectory)/test/
      /p:CollectCoverage=true
      /p:CoverletOutputFormat=opencover
      /p:CoverletOutput='$(Build.ArtifactStagingDirectory)/coverage/'
  displayName: 'dotnet test'
  workingDirectory: $(pathtosolution)

- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: '$(pathtoproject)/*.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
  displayName: 'dotnet publish'

# - script: |
#     docker build -t $(dockerId)/$(imageName) .
#     docker login -u $(dockerId) -p $(pswd)
#     docker push $(dockerId)/$(imageName)
#   env: 
#     pswd: $(dockerPassword)
#   displayName: 'docker build and push'

- task: Docker@2
  inputs:
    containerRegistry: 'NeonIconsContainerRegistry'
    repository: 'neonicons'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
  env:
    ArtifactDirectory: Build.ArtifactStagingDirectory

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Free Trial(d30e4b38-6958-43b6-ad79-a05f240c8380)'
    appType: 'webApp'
    appName: 'NeonIcons'
    package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
    deploymentMethod: 'auto'
  displayName: 'publish to server'
