# ASP.NET Core

# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'
  pathtosolution: 'Neon_Icon/'
  pathtoproject: 'Neon_Icon/WebClient'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
  workingDirectory: $(pathtosolution)
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: '$(pathtoproject)/*.csproj'
  
- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: '**\Testing.dll'
    searchFolder: '$(System.DefaultWorkingDirectory)'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Free Trial(d30e4b38-6958-43b6-ad79-a05f240c8380)'
    appType: 'webApp'
    appName: 'NeonIcons'
    package: '$(System.DefaultWorkingDirectory)/$(pathtoproject)/**/*.zip'
    deploymentMethod: 'auto'